columns:
  Applicant_Income: int64
  Loan_Amount: int64
  Credit_Score: int64
  Previous_Defaults: int64
  Interest_Rate: float64
  Number_of_Dependents: int64
  Loan_Purpose: str
  Residence_Status: str
  Home_Ownership: str
  Employment_Type: str
  Default: int64

numerical_columns:
  - Applicant_Income: int64
  - Loan_Amount: int64
  - Credit_Score: int64
  - Previous_Defaults: int64
  - Interest_Rate: float64
  - Number_of_Dependents: int64

categorical_columns:
  - Loan_Purpose: str
  - Residence_Status: str
  - Home_Ownership: str
  - Employment_Type: str

target_column: 
- Default: int64
