columns:
  Applicant_Income: int64
  Loan_Amount: int64
  Credit_Score: int64
  Previous_Defaults: int64
  Interest_Rate: float64
  Number_of_Dependents: int64
  Loan_Purpose: object
  Residence_Status: object
  Home_Ownership: object
  Employment_Type: object
  Default: int64

numerical_columns:
  - Applicant_Income
  - Loan_Amount
  - Credit_Score
  - Previous_Defaults
  - Interest_Rate
  - Number_of_Dependents

categorical_columns:
  - Loan_Purpose
  - Residence_Status
  - Home_Ownership
  - Employment_Type

target_column: Default
