name: Train, Push to DagsHub, Dockerize and Deploy

on:
  push:
    branches: [ main ]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[gs] mlflow

      - name: Configure Git for DagsHub
        run: |
          git config --global user.email "anupam848484@gmail.com"
          git config --global user.name "Anupam Anand Singh"
          git remote set-url origin https://${{ secrets.DAGSHUB_TOKEN }}@dagshub.com/AnupamKNN/LoanDefault.git

      - name: Train the model
        run: |
          python loandefault/pipeline/training_pipeline.py

      - name: Push DVC tracked files to DagsHub
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user AnupamKNN
          dvc remote modify origin --local password ${{ secrets.DAGSHUB_TOKEN }}
          dvc push

  build-and-push:
    runs-on: ubuntu-latest
    needs: train-model

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Trigger redeployment on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${RENDER_API_KEY}"
